respostas endpoints para login user products
Economarket/front-end-web-prss6 pull request #3
Opened 2022-10-05 13:17 UTC by MeiriBernardina

2022-10-05 14:05 UTC, BrunoSilvestre00 approved these changes
Falta a parte de Endereços também né, mas acredito que seja pra vocês ja irem integrando né.
Ta aprovado.

2022-10-05 16:59 UTC, MeiriBernardina commented
Isso mesmo!

2022-10-07 02:53 UTC, renan-braga approved these changes

2022-10-10 17:29 UTC, AndrezaEmiliano requested changes

2022-10-10 17:29 UTC, AndrezaEmiliano commented on src/services/models.tsx
> +  experience: Number;
experience, por não ser obrigatório, deve-se colocar um ponto de interrogação, fica assim:
experience?: Number;

Aqui no user, adicionar como opcional:
uma interface de address, uma interface de shoppingList, permissions, uma lista de tokens.

Declarar as interfaces de address e shoppingList.

2022-10-10 17:29 UTC, AndrezaEmiliano commented on src/services/models.tsx
> +  experience: Number;
qualquer dúvida, consultar a documentação atual que está neste endereço: https://docs.google.com/document/d/1IjsSpDxWZ3qQmXwgFwOBAv7Qebzx7Sa_GgohmBEQDT4/edit

2022-10-10 17:29 UTC, AndrezaEmiliano commented on src/services/models.tsx
> +
Declarar todos os uuid das entidades que a possuírem.

2022-10-10 17:29 UTC, AndrezaEmiliano commented on src/services/models.tsx
> +
Avaliar tudo o que é opcional.

2022-10-10 17:29 UTC, AndrezaEmiliano commented on src/services/models.tsx
> +}
está faltando searchName

2022-10-10 19:56 UTC, AndrezaEmiliano approved these changes

2022-10-10 19:57 UTC, merged